version: '3.8'

services:
  mlflow-server:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_server:/mlflow
      - ./mlflow_server/artifacts:/mlflow/artifacts

    command: >
      bash -c "pip install mlflow &&
      echo 'Waiting for MLflow server to start...' &&
      sleep 15 &&
      mlflow server \
      --host 0.0.0.0 \
      --port 5000 \
      --backend-store-uri sqlite:////mlflow/mlflow.db \
      --default-artifact-root /mlflow/artifacts
      "

  training:
    build: .
    depends_on:
      - mlflow-server
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./training:/app/training
      - ./mlflow_server/artifacts:/mlflow/artifacts